[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["Jonathan Pearlin <jpearlin1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
libmath = "0.2.1"
